title = "hamnghi.computer"
name = "Nghi Nguyen"
email = "hamnghi.nguyentrieu@gmail.com"

[prompt]
hostname = "hamnghi.computer"
username = "guest"

# Icons from: https://carloskiki.github.io/icondata/
# Only supports Font Awesome and Simple Icons
[stack]
frontend = [
    { name = "leptos", icon = "SiLeptos", color = "#262577" },
    { name = "html", icon = "FaHtml5Brands", color = "#e34c26" },
    { name = "tailwindcss", icon = "SiTailwindcss", color = "#06b6d4" },
]
backend = [
    { name = "rust", icon = "FaRustBrands", color = "#c45508" },
    # { name = "zig", icon = "SiZig", color = "#f7a41d" },
    { name = "go", icon = "FaGolangBrands", color = "#00add8" },
    { name = "python", icon = "FaPythonBrands", color = "#3572a5" },
    { name = "postgresql", icon = "SiPostgresql", color = "#4169e1" },
]
devops = [
    { name = "aws", icon = "FaAwsBrands", color = "#ff9900" },
    { name = "docker", icon = "FaDockerBrands", color = "#2496ed" },
    { name = "kubernetes", icon = "SiKubernetes", color = "#326ce5" },
]
tools = [
    { name = "git", icon = "FaGitAltBrands", color = "#f05032" },
    { name = "github", icon = "FaGithubBrands" },
    { name = "github-actions", icon = "SiGithubactions", color = "#2088ff" },
]

[github]
username = "nt54hamnghi"
repos = ["seaq", "sublist3r-rs", "wcli"]
in_progress = [
    { name = "sev", description = "Securely inject environment variables with secrets", language = "Rust" },
    { name = "yrc", description = "You Remember Correctly - A memorable password generator", language = "Rust" },
]

[linkedin]
username = "hamnghi"
